project:
  name: quickstart-ibm-cp-for-security
  shorten_stack_name: true
  s3_regional_buckets: false
  package_lambda: false
  s3_bucket: aws-quickstart-e2e
  regions:
  - eu-west-2
  
tests:
  cp4s:
    parameters:
      NumberOfAZs: '3'
      AvailabilityZones: $[taskcat_genaz_3]
      VPCCIDR: 10.0.0.0/16
      BootNodeAccessCIDR: override
      DomainName: override
      CPSFQDN: override
      KeyPairName: override
      NumberOfMaster: '3'
      NumberOfCompute: '3'
      AdminPassword: override
      ClusterName: cp4s-epsilon
      EnableFips: 'False'
      RedhatPullSecret: override
      APIKey: override
      APIUsername: override
      LicenseAgreement: I agree
      QSS3BucketName: aws-quickstart-e2e
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-ibm-cp-for-security/
      CP4SDeploymentLogsBucketName: override
    regions:  
    - eu-west-2
    template: templates/ibm-cloudpak-root.yaml
